// Package hostfw manages the host-side firewall for the box network.
// On macOS it uses a pf anchor, main ruleset lines, and a launchd
// boot job. All commands run through a caller-supplied Runner.
package hostfw

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// AnchorName is the pf anchor name for prison's rules.
const AnchorName = "prison"

// DaemonLabel is the launchd label for the boot job that enables
// the packet filter.
const DaemonLabel = "prison.firewall"

// Names of the staging files prison writes under the state root.
const (
	StagedRulesName  = "pf-rules"
	StagedConfName   = "pf-conf"
	StagedDaemonName = "pf-daemon.plist"
	EnableTokenName  = "pf-loaded"
)

// mainRulesetComment marks prison's lines in the main ruleset so
// they can be found and removed later.
const mainRulesetComment = "# prison, added by `prison firewall`."

// Spec describes the box network for rule generation. SubnetV6 is
// empty when the network has no IPv6.
type Spec struct {
	SubnetV4   string
	SubnetV6   string
	BrokerPort int
}

// validate checks that the spec can produce valid rules. It
// requires an IPv4 subnet and a broker port between 1 and 65535.
func (spec Spec) validate() error {
	if strings.TrimSpace(spec.SubnetV4) == "" {
		return errors.New("the box network has no IPv4 subnet, so there is nothing to write rules against; start a box with `prison up` first")
	}
	if spec.BrokerPort < 1 || spec.BrokerPort > 65535 {
		return fmt.Errorf("%d is not a usable broker port; it has to be between 1 and 65535", spec.BrokerPort)
	}
	return nil
}

// Runner runs one command and returns its combined output and error.
// Tests supply a recording runner instead of executing commands.
type Runner func(ctx context.Context, name string, args ...string) (string, error)

// SystemRunner is the Runner that executes real commands. It returns
// combined output even on failure.
func SystemRunner(ctx context.Context, name string, args ...string) (string, error) {
	output, err := exec.CommandContext(ctx, name, args...).CombinedOutput()
	if err != nil {
		return string(output), fmt.Errorf("%s: %w", name, err)
	}
	return string(output), nil
}

// State describes how much of prison's firewall is installed.
type State string

// Possible firewall states. Stale covers any partial or mismatched
// install.
const (
	StateInstalled   State = "installed"
	StateMissing     State = "missing"
	StateStale       State = "stale"
	StateUnsupported State = "unsupported"
)

// paths holds the locations of the four system files an install
// touches. Tests replace these with temporary paths.
type paths struct {
	anchorFile       string
	mainRuleset      string
	daemonFile       string
	daemonMarkerFile string
}

// systemPaths returns the real file paths on the host.
func systemPaths() paths {
	return paths{
		anchorFile:       "/etc/pf.anchors/" + AnchorName,
		mainRuleset:      "/etc/pf.conf",
		daemonFile:       "/Library/LaunchDaemons/" + DaemonLabel + ".plist",
		daemonMarkerFile: "/var/run/prison-firewall",
	}
}

// isSupportedOperatingSystem reports whether the host OS is
// supported. Only macOS is supported.
func isSupportedOperatingSystem() bool {
	return runtime.GOOS == "darwin"
}

// unsupportedError returns an error for unsupported operating systems.
func unsupportedError() error {
	return fmt.Errorf("prison has no packet filter rules to write for %s, so there is nothing to install", runtime.GOOS)
}

// Rules returns the pf anchor text for the given spec. It takes a
// Spec and returns the rule text as a string. The rules allow TCP
// to the broker port and DHCP, and block everything else.
func Rules(spec Spec) string {
	anchorFile := systemPaths().anchorFile
	var text strings.Builder
	fmt.Fprintf(&text, "# Generated by prison for the box network.\n")
	fmt.Fprintf(&text, "# Installed at %s, which the main ruleset names,\n",
		anchorFile)
	fmt.Fprintf(&text, "# so the system loads these at every boot.\n")
	fmt.Fprintf(&text,
		"pass in quick inet proto tcp from %s to any port %d\n",
		spec.SubnetV4, spec.BrokerPort)
	fmt.Fprintf(&text,
		"pass in quick inet proto udp from %s to any port 67\n",
		spec.SubnetV4)
	fmt.Fprintf(&text, "block drop in quick inet from %s to any\n",
		spec.SubnetV4)
	if spec.SubnetV6 != "" {
		fmt.Fprintf(&text,
			"# Neighbour discovery keeps the box's address usable.\n")
		fmt.Fprintf(&text,
			"pass in quick inet6 proto ipv6-icmp from %s to any\n",
			spec.SubnetV6)
		fmt.Fprintf(&text, "block drop in quick inet6 from %s to any\n",
			spec.SubnetV6)
	}
	return text.String()
}

// ReadCommand returns the shell command to read prison's loaded
// rules.
func ReadCommand() string {
	return fmt.Sprintf("sudo pfctl -a %s -sr", AnchorName)
}

// Describe returns a list of strings describing what Install would
// do. Each line names a file written or command run.
func Describe(spec Spec) []string {
	p := systemPaths()
	lines := []string{
		fmt.Sprintf("refuses everything from %s except tcp to port %d and dhcp",
			spec.SubnetV4, spec.BrokerPort),
	}
	if spec.SubnetV6 != "" {
		lines = append(lines, fmt.Sprintf(
			"refuses everything from %s except neighbour discovery",
			spec.SubnetV6))
	}
	return append(lines,
		fmt.Sprintf("writes %s, those rules, owned by root", p.anchorFile),
		fmt.Sprintf("writes %s, three lines loading them at every boot",
			p.mainRuleset),
		fmt.Sprintf("writes %s, a job turning the filter on, which macOS leaves undone",
			p.daemonFile),
		fmt.Sprintf("runs sudo pfctl -f %s", p.mainRuleset),
		"runs sudo pfctl -E",
		"undo with `prison host firewall --remove`",
	)
}

// mainRulesetLines returns the three lines that load prison's anchor
// at boot.
func mainRulesetLines(p paths) []string {
	return []string{
		mainRulesetComment,
		fmt.Sprintf("anchor %q", AnchorName),
		loadAnchorLine(p),
	}
}

// loadAnchorLine returns the line that loads prison's anchor file.
func loadAnchorLine(p paths) string {
	return fmt.Sprintf("load anchor %q from %q", AnchorName, p.anchorFile)
}

// readMainRuleset returns the current main ruleset contents. A
// missing file returns an empty string, not an error.
func readMainRuleset(p paths) (string, error) {
	content, err := os.ReadFile(p.mainRuleset)
	if errors.Is(err, os.ErrNotExist) {
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("could not read %s: %w", p.mainRuleset, err)
	}
	return string(content), nil
}

// mainRulesetWithoutPrisonLines returns the ruleset with prison's
// lines removed.
func mainRulesetWithoutPrisonLines(content string, p paths) string {
	prisonLines := mainRulesetLines(p)
	var kept []string
	for _, line := range strings.Split(content, "\n") {
		isPrisonLine := false
		for _, prisonLine := range prisonLines {
			if line == prisonLine {
				isPrisonLine = true
				break
			}
		}
		if !isPrisonLine {
			kept = append(kept, line)
		}
	}
	return endWithNewline(strings.Join(kept, "\n"))
}

// mainRulesetWithPrisonLines returns the ruleset with prison's lines
// appended. Existing copies are removed first.
func mainRulesetWithPrisonLines(content string, p paths) string {
	stripped := mainRulesetWithoutPrisonLines(content, p)
	return stripped + strings.Join(mainRulesetLines(p), "\n") + "\n"
}

// mainRulesetCarriesAnchor reports whether the ruleset already loads
// prison's anchor.
func mainRulesetCarriesAnchor(content string, p paths) bool {
	wanted := loadAnchorLine(p)
	for _, line := range strings.Split(content, "\n") {
		if line == wanted {
			return true
		}
	}
	return false
}

// endWithNewline adds a trailing newline if the text has none.
// Empty text stays empty.
func endWithNewline(text string) string {
	if text == "" || strings.HasSuffix(text, "\n") {
		return text
	}
	return text + "\n"
}

// daemonPlist returns the launchd property list XML for the boot
// job. The job enables the filter and records its token.
func daemonPlist(p paths) string {
	command := fmt.Sprintf(
		"/sbin/pfctl -E 2&gt;&amp;1 | /usr/bin/awk '/Token/ { print $NF; exit }' &gt; %s",
		p.daemonMarkerFile)
	return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>` + DaemonLabel + `</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>-c</string>
    <string>` + command + `</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
`
}

// writeStagedFile writes content to a staging file under stagingDir.
// It returns the file path or an error.
func writeStagedFile(stagingDir, name, content string) (string, error) {
	if err := os.MkdirAll(stagingDir, 0o700); err != nil {
		return "", fmt.Errorf("could not create %s: %w", stagingDir, err)
	}
	path := filepath.Join(stagingDir, name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("could not write %s: %w", path, err)
	}
	return path, nil
}

// parseEnableToken extracts the pf reference token from `pfctl -E`
// output. It returns an empty string if no token is found.
func parseEnableToken(output string) string {
	for _, line := range strings.Split(output, "\n") {
		if !strings.Contains(line, "Token") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		return fields[len(fields)-1]
	}
	return ""
}

// installAsRoot copies source to target with root ownership via sudo.
func installAsRoot(ctx context.Context, run Runner, source, target string) error {
	_, err := run(ctx, "sudo", "install", "-m", "0644", "-o", "root",
		"-g", "wheel", source, target)
	if err != nil {
		return fmt.Errorf("could not write %s: %w", target, err)
	}
	return nil
}

// Status reports the current firewall state. It takes a spec,
// staging directory, and runner. It returns a State and an error.
func Status(ctx context.Context, spec Spec, stagingDir string, run Runner) (State, error) {
	if !isSupportedOperatingSystem() {
		return StateUnsupported, nil
	}
	if err := spec.validate(); err != nil {
		return StateMissing, err
	}
	return status(ctx, spec, stagingDir, systemPaths(), run)
}

// status is Status without the OS check, for testing with custom
// paths.
func status(ctx context.Context, spec Spec, stagingDir string, p paths, run Runner) (State, error) {
	anchorContent, err := os.ReadFile(p.anchorFile)
	anchorMissing := errors.Is(err, os.ErrNotExist)
	if err != nil && !anchorMissing {
		return StateMissing, fmt.Errorf("could not read %s: %w",
			p.anchorFile, err)
	}
	ruleset, err := readMainRuleset(p)
	if err != nil {
		return StateMissing, err
	}
	carriesAnchor := mainRulesetCarriesAnchor(ruleset, p)
	daemonInstalled := fileExists(p.daemonFile)

	if anchorMissing && !carriesAnchor && !daemonInstalled {
		return StateMissing, nil
	}
	if anchorMissing || !carriesAnchor || !daemonInstalled {
		return StateStale, nil
	}
	if string(anchorContent) != Rules(spec) {
		return StateStale, nil
	}

	loaded, err := run(ctx, "pfctl", "-a", AnchorName, "-sr")
	if err != nil {
		if fileExists(filepath.Join(stagingDir, EnableTokenName)) {
			return StateInstalled, nil
		}
		return StateStale, nil
	}
	if strings.TrimSpace(loaded) == "" {
		return StateStale, nil
	}
	return StateInstalled, nil
}

// fileExists reports whether path exists as a readable file.
func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// Install writes, validates, and installs the firewall rules. It
// takes a spec, staging directory, runner, and output writer.
// It returns an error if any step fails.
func Install(ctx context.Context, spec Spec, stagingDir string, run Runner, out io.Writer) error {
	if !isSupportedOperatingSystem() {
		return unsupportedError()
	}
	if err := spec.validate(); err != nil {
		return err
	}
	return install(ctx, spec, stagingDir, systemPaths(), run, out)
}

// install is Install without the OS check, for testing with custom
// paths.
func install(ctx context.Context, spec Spec, stagingDir string, p paths, run Runner, out io.Writer) error {
	rulesPath, err := writeStagedFile(stagingDir, StagedRulesName, Rules(spec))
	if err != nil {
		return err
	}
	if _, err := run(ctx, "pfctl", "-nf", rulesPath); err != nil {
		return fmt.Errorf("prison generated rules the packet filter will not parse; they are at %s: %w", rulesPath, err)
	}
	if err := installAsRoot(ctx, run, rulesPath, p.anchorFile); err != nil {
		return err
	}

	ruleset, err := readMainRuleset(p)
	if err != nil {
		return err
	}
	confPath, err := writeStagedFile(stagingDir, StagedConfName,
		mainRulesetWithPrisonLines(ruleset, p))
	if err != nil {
		return err
	}
	// The system rejects the whole ruleset if anything fails to parse,
	// so it must be checked as a whole.
	if _, err := run(ctx, "pfctl", "-n", "-f", confPath); err != nil {
		return fmt.Errorf("the main ruleset with prison's anchor added does not parse; it is at %s, and %s was left alone: %w", confPath, p.mainRuleset, err)
	}
	if err := installAsRoot(ctx, run, confPath, p.mainRuleset); err != nil {
		return err
	}

	daemonPath, err := writeStagedFile(stagingDir, StagedDaemonName,
		daemonPlist(p))
	if err != nil {
		return err
	}
	run(ctx, "sudo", "launchctl", "bootout", "system/"+DaemonLabel)
	if err := installAsRoot(ctx, run, daemonPath, p.daemonFile); err != nil {
		return err
	}
	if _, err := run(ctx, "sudo", "launchctl", "bootstrap", "system",
		p.daemonFile); err != nil {
		if _, err := run(ctx, "sudo", "launchctl", "load", "-w",
			p.daemonFile); err != nil {
			fmt.Fprintf(out, "warn: launchd refused the job at %s, so the rules will load after a reboot but the filter will not be on. Run `prison firewall` again once it is.\n", p.daemonFile)
		}
	}

	fmt.Fprintf(out, "==> reloading the main ruleset\n")
	fmt.Fprintf(out, "warn: anything another tool inserted into it while running, a VPN or internet sharing among them, is dropped and has to be re-added by restarting that tool.\n")
	if _, err := run(ctx, "sudo", "pfctl", "-f", p.mainRuleset); err != nil {
		return fmt.Errorf("the main ruleset was refused; prison's rules are installed at %s but nothing is loaded: %w", p.anchorFile, err)
	}

	return holdEnableReference(ctx, stagingDir, run)
}

// holdEnableReference enables the filter, records the new token,
// and releases the previous one.
func holdEnableReference(ctx context.Context, stagingDir string, run Runner) error {
	tokenPath := filepath.Join(stagingDir, EnableTokenName)
	previous, _ := os.ReadFile(tokenPath)
	previousToken := strings.TrimSpace(string(previous))

	output, _ := run(ctx, "sudo", "pfctl", "-E")
	token := parseEnableToken(output)
	if err := os.WriteFile(tokenPath, []byte(token+"\n"), 0o600); err != nil {
		return fmt.Errorf("could not write %s: %w", tokenPath, err)
	}
	if previousToken != "" && previousToken != token {
		run(ctx, "sudo", "pfctl", "-X", previousToken)
	}
	return nil
}

// Remove uninstalls prison's firewall rules. It takes a spec,
// staging directory, runner, and output writer. Non-fatal failures
// are warned on out instead of returned.
func Remove(ctx context.Context, spec Spec, stagingDir string, run Runner, out io.Writer) error {
	if !isSupportedOperatingSystem() {
		return unsupportedError()
	}
	return remove(ctx, stagingDir, systemPaths(), run, out)
}

// remove is Remove without the OS check, for testing with custom
// paths.
func remove(ctx context.Context, stagingDir string, p paths, run Runner, out io.Writer) error {
	bootTokenOutput, err := run(ctx, "sudo", "cat", p.daemonMarkerFile)
	bootToken := ""
	if err == nil {
		bootToken = strings.TrimSpace(bootTokenOutput)
	}

	run(ctx, "sudo", "launchctl", "bootout", "system/"+DaemonLabel)
	run(ctx, "sudo", "launchctl", "unload", "-w", p.daemonFile)
	run(ctx, "sudo", "rm", "-f", p.daemonFile, p.daemonMarkerFile)

	ruleset, err := readMainRuleset(p)
	if err != nil {
		return err
	}
	if mainRulesetCarriesAnchor(ruleset, p) {
		confPath, err := writeStagedFile(stagingDir, StagedConfName,
			mainRulesetWithoutPrisonLines(ruleset, p))
		if err != nil {
			return err
		}
		if err := installAsRoot(ctx, run, confPath, p.mainRuleset); err != nil {
			fmt.Fprintf(out, "warn: could not take prison's lines out of %s, so they are still there.\n", p.mainRuleset)
		}
	}
	run(ctx, "sudo", "rm", "-f", p.anchorFile)

	run(ctx, "sudo", "pfctl", "-a", AnchorName, "-F", "rules")
	run(ctx, "sudo", "pfctl", "-f", p.mainRuleset)

	tokenPath := filepath.Join(stagingDir, EnableTokenName)
	held, _ := os.ReadFile(tokenPath)
	// Release prison's own pf references without disabling the filter
	// for other users.
	for _, token := range []string{strings.TrimSpace(string(held)), bootToken} {
		if token == "" {
			continue
		}
		run(ctx, "sudo", "pfctl", "-X", token)
	}
	if err := os.Remove(tokenPath); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("could not remove %s: %w", tokenPath, err)
	}
	return nil
}
