package hostfw

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// recordingRunner records commands in order and returns preconfigured
// replies. Commands listed in failures return an error.
type recordingRunner struct {
	commands []string
	replies  map[string]string
	failures map[string]bool
}

// run records the command and returns the configured reply.
func (runner *recordingRunner) run(ctx context.Context, name string, args ...string) (string, error) {
	command := strings.TrimSpace(name + " " + strings.Join(args, " "))
	runner.commands = append(runner.commands, command)
	if runner.failures[command] {
		return runner.replies[command], os.ErrPermission
	}
	return runner.replies[command], nil
}

// newRecordingRunner returns a runner that succeeds at everything
// with empty output.
func newRecordingRunner() *recordingRunner {
	return &recordingRunner{
		replies:  map[string]string{},
		failures: map[string]bool{},
	}
}

// newTestPaths returns paths under a temporary directory with all
// parent directories created.
func newTestPaths(t *testing.T) paths {
	t.Helper()
	root := t.TempDir()
	p := paths{
		anchorFile:  filepath.Join(root, "etc/pf.anchors/prison"),
		mainRuleset: filepath.Join(root, "etc/pf.conf"),
		daemonFile: filepath.Join(root,
			"Library/LaunchDaemons/prison.firewall.plist"),
		daemonMarkerFile: filepath.Join(root, "var/run/prison-firewall"),
	}
	everyFile := []string{
		p.anchorFile, p.mainRuleset, p.daemonFile, p.daemonMarkerFile,
	}
	for _, path := range everyFile {
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatalf("could not create %s: %v", filepath.Dir(path), err)
		}
	}
	return p
}

// writeFile writes content to path. Fails the test on error.
func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("could not write %s: %v", path, err)
	}
}

// checkCommands compares recorded commands against the expected list
// in order.
func checkCommands(t *testing.T, got, want []string) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("ran %d commands, want %d:\ngot:  %s\nwant: %s",
			len(got), len(want), strings.Join(got, "\n      "),
			strings.Join(want, "\n      "))
	}
	for index := range want {
		if got[index] != want[index] {
			t.Errorf("command %d is %q, want %q", index, got[index], want[index])
		}
	}
}

// ipv4Spec is the default spec: one IPv4 subnet and broker port.
var ipv4Spec = Spec{SubnetV4: "192.168.64.0/24", BrokerPort: 8787}

// TestRulesForIPv4OnlySpec checks the anchor text for an IPv4-only
// network.
func TestRulesForIPv4OnlySpec(t *testing.T) {
	want := `# Generated by prison for the box network.
# Installed at /etc/pf.anchors/prison, which the main ruleset names,
# so the system loads these at every boot.
pass in quick inet proto tcp from 192.168.64.0/24 to any port 8787
pass in quick inet proto udp from 192.168.64.0/24 to any port 67
block drop in quick inet from 192.168.64.0/24 to any
`
	if got := Rules(ipv4Spec); got != want {
		t.Errorf("rules are:\n%s\nwant:\n%s", got, want)
	}
}

// TestRulesForDualStackSpec checks that an IPv6 subnet adds
// neighbour discovery and a block rule.
func TestRulesForDualStackSpec(t *testing.T) {
	spec := Spec{
		SubnetV4:   "192.168.64.0/24",
		SubnetV6:   "fd00:beef::/64",
		BrokerPort: 8787,
	}
	want := Rules(ipv4Spec) + `# Neighbour discovery keeps the box's address usable.
pass in quick inet6 proto ipv6-icmp from fd00:beef::/64 to any
block drop in quick inet6 from fd00:beef::/64 to any
`
	if got := Rules(spec); got != want {
		t.Errorf("rules are:\n%s\nwant:\n%s", got, want)
	}
}

// TestSpecValidation checks refusal of missing subnets and out-of-
// range broker ports.
func TestSpecValidation(t *testing.T) {
	cases := []struct {
		name  string
		spec  Spec
		fails bool
	}{
		{name: "good", spec: ipv4Spec},
		{name: "no subnet", spec: Spec{BrokerPort: 8787}, fails: true},
		{name: "port zero", spec: Spec{SubnetV4: "10.0.0.0/24"}, fails: true},
		{
			name:  "port too high",
			spec:  Spec{SubnetV4: "10.0.0.0/24", BrokerPort: 70000},
			fails: true,
		},
	}
	for _, testCase := range cases {
		err := testCase.spec.validate()
		if testCase.fails && err == nil {
			t.Errorf("%s: want an error, got none", testCase.name)
		}
		if !testCase.fails && err != nil {
			t.Errorf("%s: %v", testCase.name, err)
		}
	}
}

// TestDescribeNamesEveryEffect checks that the description mentions
// every file, command, and subnet.
func TestDescribeNamesEveryEffect(t *testing.T) {
	lines := strings.Join(Describe(ipv4Spec), "\n")
	for _, wanted := range []string{
		"192.168.64.0/24", "8787",
		"/etc/pf.anchors/prison", "/etc/pf.conf",
		"/Library/LaunchDaemons/prison.firewall.plist",
		"sudo pfctl -f /etc/pf.conf", "sudo pfctl -E",
		"prison host firewall --remove",
	} {
		if !strings.Contains(lines, wanted) {
			t.Errorf("the description does not mention %q:\n%s", wanted, lines)
		}
	}
	if strings.Contains(lines, "neighbour discovery") {
		t.Error("an IPv4-only spec should not describe IPv6 rules")
	}
	if !strings.Contains(strings.Join(Describe(Spec{
		SubnetV4:   "192.168.64.0/24",
		SubnetV6:   "fd00::/64",
		BrokerPort: 8787,
	}), "\n"), "fd00::/64") {
		t.Error("a dual stack spec should describe the IPv6 subnet")
	}
}

// installEverything writes all three system files as a finished
// install would.
func installEverything(t *testing.T, spec Spec, p paths) {
	t.Helper()
	writeFile(t, p.anchorFile, Rules(spec))
	writeFile(t, p.mainRuleset,
		mainRulesetWithPrisonLines("scrub-anchor \"com.apple/*\"\n", p))
	writeFile(t, p.daemonFile, daemonPlist(p))
}

// TestStatusTransitions checks the status through missing, installed,
// and stale states.
func TestStatusTransitions(t *testing.T) {
	ctx := context.Background()
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	runner := newRecordingRunner()
	runner.replies["pfctl -a prison -sr"] =
		"block drop in quick inet from 192.168.64.0/24 to any\n"

	writeFile(t, p.mainRuleset, "scrub-anchor \"com.apple/*\"\n")
	state, err := status(ctx, ipv4Spec, stagingDir, p, runner.run)
	if err != nil {
		t.Fatalf("status: %v", err)
	}
	if state != StateMissing {
		t.Errorf("with nothing installed the state is %q, want %q",
			state, StateMissing)
	}

	installEverything(t, ipv4Spec, p)
	state, err = status(ctx, ipv4Spec, stagingDir, p, runner.run)
	if err != nil {
		t.Fatalf("status: %v", err)
	}
	if state != StateInstalled {
		t.Errorf("with everything installed the state is %q, want %q",
			state, StateInstalled)
	}

	writeFile(t, p.anchorFile, Rules(Spec{
		SubnetV4:   "192.168.64.0/24",
		BrokerPort: 9999,
	}))
	state, _ = status(ctx, ipv4Spec, stagingDir, p, runner.run)
	if state != StateStale {
		t.Errorf("with an anchor for another port the state is %q, want %q",
			state, StateStale)
	}

	installEverything(t, ipv4Spec, p)
	writeFile(t, p.mainRuleset, "scrub-anchor \"com.apple/*\"\n")
	state, _ = status(ctx, ipv4Spec, stagingDir, p, runner.run)
	if state != StateStale {
		t.Errorf("with the main ruleset edited the state is %q, want %q",
			state, StateStale)
	}

	installEverything(t, ipv4Spec, p)
	if err := os.Remove(p.daemonFile); err != nil {
		t.Fatalf("could not remove the boot job: %v", err)
	}
	state, _ = status(ctx, ipv4Spec, stagingDir, p, runner.run)
	if state != StateStale {
		t.Errorf("without the boot job the state is %q, want %q",
			state, StateStale)
	}
}

// TestStatusWhenTheFilterCannotBeRead checks that the enable token
// decides the status when the filter cannot be queried.
func TestStatusWhenTheFilterCannotBeRead(t *testing.T) {
	ctx := context.Background()
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	installEverything(t, ipv4Spec, p)

	runner := newRecordingRunner()
	runner.failures["pfctl -a prison -sr"] = true
	state, err := status(ctx, ipv4Spec, stagingDir, p, runner.run)
	if err != nil {
		t.Fatalf("status: %v", err)
	}
	if state != StateStale {
		t.Errorf("without an enable token the state is %q, want %q",
			state, StateStale)
	}

	writeFile(t, filepath.Join(stagingDir, EnableTokenName), "17\n")
	state, _ = status(ctx, ipv4Spec, stagingDir, p, runner.run)
	if state != StateInstalled {
		t.Errorf("with an enable token the state is %q, want %q",
			state, StateInstalled)
	}
}

// TestStatusWhenNothingIsLoaded checks that installed files with no
// loaded rules read as stale.
func TestStatusWhenNothingIsLoaded(t *testing.T) {
	p := newTestPaths(t)
	installEverything(t, ipv4Spec, p)
	runner := newRecordingRunner()
	state, err := status(context.Background(), ipv4Spec, t.TempDir(), p,
		runner.run)
	if err != nil {
		t.Fatalf("status: %v", err)
	}
	if state != StateStale {
		t.Errorf("with an empty anchor loaded the state is %q, want %q",
			state, StateStale)
	}
}

// TestInstallCommandSequence checks every command an install runs
// and the staged files it produces.
func TestInstallCommandSequence(t *testing.T) {
	ctx := context.Background()
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	writeFile(t, p.mainRuleset, "scrub-anchor \"com.apple/*\"\n")

	runner := newRecordingRunner()
	runner.replies["sudo pfctl -E"] = "pf enabled\nToken : 4242\n"
	var out strings.Builder
	if err := install(ctx, ipv4Spec, stagingDir, p, runner.run, &out); err != nil {
		t.Fatalf("install: %v", err)
	}

	rulesPath := filepath.Join(stagingDir, StagedRulesName)
	confPath := filepath.Join(stagingDir, StagedConfName)
	daemonPath := filepath.Join(stagingDir, StagedDaemonName)
	installArguments := "sudo install -m 0644 -o root -g wheel "
	checkCommands(t, runner.commands, []string{
		"pfctl -nf " + rulesPath,
		installArguments + rulesPath + " " + p.anchorFile,
		"pfctl -n -f " + confPath,
		installArguments + confPath + " " + p.mainRuleset,
		"sudo launchctl bootout system/prison.firewall",
		installArguments + daemonPath + " " + p.daemonFile,
		"sudo launchctl bootstrap system " + p.daemonFile,
		"sudo pfctl -f " + p.mainRuleset,
		"sudo pfctl -E",
	})

	staged, err := os.ReadFile(rulesPath)
	if err != nil {
		t.Fatalf("could not read the staged rules: %v", err)
	}
	if string(staged) != Rules(ipv4Spec) {
		t.Errorf("the staged rules are:\n%s", staged)
	}
	conf, err := os.ReadFile(confPath)
	if err != nil {
		t.Fatalf("could not read the staged main ruleset: %v", err)
	}
	want := "scrub-anchor \"com.apple/*\"\n" + mainRulesetComment + "\n" +
		"anchor \"prison\"\n" +
		"load anchor \"prison\" from \"" + p.anchorFile + "\"\n"
	if string(conf) != want {
		t.Errorf("the staged main ruleset is:\n%s\nwant:\n%s", conf, want)
	}
	plist, err := os.ReadFile(daemonPath)
	if err != nil {
		t.Fatalf("could not read the staged boot job: %v", err)
	}
	for _, wanted := range []string{
		"<string>prison.firewall</string>", "/sbin/pfctl -E",
		p.daemonMarkerFile,
	} {
		if !strings.Contains(string(plist), wanted) {
			t.Errorf("the boot job does not mention %q", wanted)
		}
	}
	token, err := os.ReadFile(filepath.Join(stagingDir, EnableTokenName))
	if err != nil {
		t.Fatalf("could not read the enable token: %v", err)
	}
	if strings.TrimSpace(string(token)) != "4242" {
		t.Errorf("the recorded enable token is %q, want %q", token, "4242")
	}
	if !strings.Contains(out.String(), "reloading the main ruleset") ||
		!strings.Contains(out.String(), "is dropped") {
		t.Errorf("install did not warn before the reload:\n%s", out.String())
	}
}

// TestInstallReleasesThePreviousToken checks that a second install
// acquires a new token and releases the old one.
func TestInstallReleasesThePreviousToken(t *testing.T) {
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	writeFile(t, p.mainRuleset, "")
	writeFile(t, filepath.Join(stagingDir, EnableTokenName), "11\n")

	runner := newRecordingRunner()
	runner.replies["sudo pfctl -E"] = "Token : 12\n"
	err := install(context.Background(), ipv4Spec, stagingDir, p, runner.run,
		&strings.Builder{})
	if err != nil {
		t.Fatalf("install: %v", err)
	}
	last := runner.commands[len(runner.commands)-1]
	if last != "sudo pfctl -X 11" {
		t.Errorf("the last command is %q, want %q", last, "sudo pfctl -X 11")
	}
}

// TestInstallStopsWhenTheMainRulesetWouldNotParse checks that a
// refused ruleset leaves the system file unchanged.
func TestInstallStopsWhenTheMainRulesetWouldNotParse(t *testing.T) {
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	writeFile(t, p.mainRuleset, "scrub-anchor \"com.apple/*\"\n")

	runner := newRecordingRunner()
	runner.failures["pfctl -n -f "+filepath.Join(stagingDir, StagedConfName)] = true
	err := install(context.Background(), ipv4Spec, stagingDir, p, runner.run,
		&strings.Builder{})
	if err == nil {
		t.Fatal("want an error, got none")
	}
	if !strings.Contains(err.Error(), p.mainRuleset) {
		t.Errorf("the error does not name the main ruleset: %v", err)
	}
	for _, command := range runner.commands {
		if strings.Contains(command, "pfctl -f") {
			t.Errorf("the ruleset was reloaded anyway: %q", command)
		}
	}
}

// TestInstallWarnsWhenLaunchdRefusesTheJob checks the fallback to
// the older load command and the warning on failure.
func TestInstallWarnsWhenLaunchdRefusesTheJob(t *testing.T) {
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	writeFile(t, p.mainRuleset, "")

	runner := newRecordingRunner()
	runner.failures["sudo launchctl bootstrap system "+p.daemonFile] = true
	runner.failures["sudo launchctl load -w "+p.daemonFile] = true
	var out strings.Builder
	err := install(context.Background(), ipv4Spec, stagingDir, p, runner.run,
		&out)
	if err != nil {
		t.Fatalf("install: %v", err)
	}
	if !strings.Contains(out.String(), "launchd refused the job") {
		t.Errorf("install did not warn about launchd:\n%s", out.String())
	}
}

// TestRemoveCommandSequence checks every command removal runs and
// that the main ruleset is restored.
func TestRemoveCommandSequence(t *testing.T) {
	ctx := context.Background()
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	installEverything(t, ipv4Spec, p)
	writeFile(t, filepath.Join(stagingDir, EnableTokenName), "4242\n")

	runner := newRecordingRunner()
	runner.replies["sudo cat "+p.daemonMarkerFile] = "77\n"
	if err := remove(ctx, stagingDir, p, runner.run, &strings.Builder{}); err != nil {
		t.Fatalf("remove: %v", err)
	}

	confPath := filepath.Join(stagingDir, StagedConfName)
	checkCommands(t, runner.commands, []string{
		"sudo cat " + p.daemonMarkerFile,
		"sudo launchctl bootout system/prison.firewall",
		"sudo launchctl unload -w " + p.daemonFile,
		"sudo rm -f " + p.daemonFile + " " + p.daemonMarkerFile,
		"sudo install -m 0644 -o root -g wheel " + confPath + " " + p.mainRuleset,
		"sudo rm -f " + p.anchorFile,
		"sudo pfctl -a prison -F rules",
		"sudo pfctl -f " + p.mainRuleset,
		"sudo pfctl -X 4242",
		"sudo pfctl -X 77",
	})

	conf, err := os.ReadFile(confPath)
	if err != nil {
		t.Fatalf("could not read the staged main ruleset: %v", err)
	}
	if string(conf) != "scrub-anchor \"com.apple/*\"\n" {
		t.Errorf("the staged main ruleset is:\n%s", conf)
	}
	if _, err := os.Stat(filepath.Join(stagingDir, EnableTokenName)); err == nil {
		t.Error("the enable token file is still there")
	}
}

// TestRemoveWithNothingInstalled checks that removal skips the
// ruleset edit and token release when nothing is installed.
func TestRemoveWithNothingInstalled(t *testing.T) {
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	writeFile(t, p.mainRuleset, "scrub-anchor \"com.apple/*\"\n")

	runner := newRecordingRunner()
	runner.failures["sudo cat "+p.daemonMarkerFile] = true
	if err := remove(context.Background(), stagingDir, p, runner.run,
		&strings.Builder{}); err != nil {
		t.Fatalf("remove: %v", err)
	}
	checkCommands(t, runner.commands, []string{
		"sudo cat " + p.daemonMarkerFile,
		"sudo launchctl bootout system/prison.firewall",
		"sudo launchctl unload -w " + p.daemonFile,
		"sudo rm -f " + p.daemonFile + " " + p.daemonMarkerFile,
		"sudo rm -f " + p.anchorFile,
		"sudo pfctl -a prison -F rules",
		"sudo pfctl -f " + p.mainRuleset,
	})
}

// TestRemoveWarnsWhenTheMainRulesetCannotBeWritten checks that a
// failed ruleset write warns and continues.
func TestRemoveWarnsWhenTheMainRulesetCannotBeWritten(t *testing.T) {
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	installEverything(t, ipv4Spec, p)

	runner := newRecordingRunner()
	confPath := filepath.Join(stagingDir, StagedConfName)
	runner.failures["sudo install -m 0644 -o root -g wheel "+confPath+" "+
		p.mainRuleset] = true
	var out strings.Builder
	if err := remove(context.Background(), stagingDir, p, runner.run, &out); err != nil {
		t.Fatalf("remove: %v", err)
	}
	if !strings.Contains(out.String(), "could not take prison's lines out") {
		t.Errorf("remove did not warn:\n%s", out.String())
	}
}

// TestMainRulesetEditsAreReversible checks that adding and removing
// prison's lines is a round trip, and adding twice is idempotent.
func TestMainRulesetEditsAreReversible(t *testing.T) {
	p := systemPaths()
	original := "scrub-anchor \"com.apple/*\"\nanchor \"com.apple/*\"\n"
	added := mainRulesetWithPrisonLines(original, p)
	if !mainRulesetCarriesAnchor(added, p) {
		t.Fatalf("the anchor is not there after adding it:\n%s", added)
	}
	if again := mainRulesetWithPrisonLines(added, p); again != added {
		t.Errorf("adding twice gives:\n%s\nwant:\n%s", again, added)
	}
	back := mainRulesetWithoutPrisonLines(added, p)
	if back != original {
		t.Errorf("removal gives:\n%s\nwant:\n%s", back, original)
	}
	if mainRulesetCarriesAnchor(original, p) {
		t.Error("a ruleset without prison's lines reads as carrying them")
	}
}

// TestParseEnableToken checks token extraction from pfctl output.
func TestParseEnableToken(t *testing.T) {
	cases := map[string]string{
		"pf enabled\nToken : 4242\n":       "4242",
		"pfctl: pf already enabled\n":      "",
		"Token : 1\nToken : 2\n":           "1",
		"":                                 "",
		"No ALTQ support in kernel\nT : 9": "",
	}
	for output, want := range cases {
		if got := parseEnableToken(output); got != want {
			t.Errorf("the token in %q is %q, want %q", output, got, want)
		}
	}
}

// TestUnsupportedHost checks that exported functions refuse to run
// on hosts without a supported packet filter.
func TestUnsupportedHost(t *testing.T) {
	if isSupportedOperatingSystem() {
		t.Skip("this host has an implemented packet filter")
	}
	ctx := context.Background()
	runner := newRecordingRunner()
	state, err := Status(ctx, ipv4Spec, t.TempDir(), runner.run)
	if err != nil || state != StateUnsupported {
		t.Errorf("status is %q with error %v, want %q and none",
			state, err, StateUnsupported)
	}
	if err := Install(ctx, ipv4Spec, t.TempDir(), runner.run,
		&strings.Builder{}); err == nil {
		t.Error("install should refuse")
	}
	if err := Remove(ctx, ipv4Spec, t.TempDir(), runner.run,
		&strings.Builder{}); err == nil {
		t.Error("remove should refuse")
	}
	if len(runner.commands) != 0 {
		t.Errorf("commands were run anyway: %v", runner.commands)
	}
}
