package hostfw

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

type recordingRunner struct {
	commands []string
	replies  map[string]string
	failures map[string]bool
}

func (runner *recordingRunner) run(ctx context.Context, name string, args ...string) (string, error) {
	command := strings.TrimSpace(name + " " + strings.Join(args, " "))
	runner.commands = append(runner.commands, command)
	if runner.failures[command] {
		return runner.replies[command], os.ErrPermission
	}
	return runner.replies[command], nil
}

func newRecordingRunner() *recordingRunner {
	return &recordingRunner{
		replies:  map[string]string{},
		failures: map[string]bool{},
	}
}

func newTestPaths(t *testing.T) paths {
	t.Helper()
	root := t.TempDir()
	p := paths{
		anchorFile:  filepath.Join(root, "etc/pf.anchors/prison"),
		mainRuleset: filepath.Join(root, "etc/pf.conf"),
		daemonFile: filepath.Join(root,
			"Library/LaunchDaemons/prison.firewall.plist"),
		daemonMarkerFile: filepath.Join(root, "var/run/prison-firewall"),
	}
	everyFile := []string{
		p.anchorFile, p.mainRuleset, p.daemonFile, p.daemonMarkerFile,
	}
	for _, path := range everyFile {
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatalf("cannot create %s: %v", filepath.Dir(path), err)
		}
	}
	return p
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("cannot write %s: %v", path, err)
	}
}

func checkCommands(t *testing.T, got, want []string) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("ran %d commands, want %d\ngot:  %s\nwant: %s",
			len(got), len(want), strings.Join(got, "\n      "),
			strings.Join(want, "\n      "))
	}
	for index := range want {
		if got[index] != want[index] {
			t.Errorf("command %d = %q, want %q", index, got[index], want[index])
		}
	}
}

var ipv4Spec = Spec{SubnetV4: "192.168.64.0/24", BrokerPort: 8787}

func TestRulesForIPv4OnlySpec(t *testing.T) {
	want := `# Generated by prison for the box network.
# Installed at /etc/pf.anchors/prison, which the main ruleset names,
# so the system loads these at every boot.
pass in quick inet proto tcp from 192.168.64.0/24 to any port 8787
pass in quick inet proto udp from 192.168.64.0/24 to any port 67
block drop in quick inet from 192.168.64.0/24 to any
`
	if got := pfRules(ipv4Spec); got != want {
		t.Errorf("pfRules =\n%s\nwant:\n%s", got, want)
	}
}

func TestRulesForDualStackSpec(t *testing.T) {
	spec := Spec{
		SubnetV4:   "192.168.64.0/24",
		SubnetV6:   "fd00:beef::/64",
		BrokerPort: 8787,
	}
	want := pfRules(ipv4Spec) + `# Neighbour discovery keeps the box's address usable.
pass in quick inet6 proto ipv6-icmp from fd00:beef::/64 to any
block drop in quick inet6 from fd00:beef::/64 to any
`
	if got := pfRules(spec); got != want {
		t.Errorf("pfRules =\n%s\nwant:\n%s", got, want)
	}
}

func TestSpecValidation(t *testing.T) {
	cases := []struct {
		name  string
		spec  Spec
		fails bool
	}{
		{name: "good", spec: ipv4Spec},
		{name: "no subnet", spec: Spec{BrokerPort: 8787}, fails: true},
		{name: "port zero", spec: Spec{SubnetV4: "10.0.0.0/24"}, fails: true},
		{
			name:  "port too high",
			spec:  Spec{SubnetV4: "10.0.0.0/24", BrokerPort: 70000},
			fails: true,
		},
	}
	for _, testCase := range cases {
		err := testCase.spec.validate()
		if testCase.fails && err == nil {
			t.Errorf("%s: validate = nil, want an error", testCase.name)
		}
		if !testCase.fails && err != nil {
			t.Errorf("%s: validate = %v, want nil", testCase.name, err)
		}
	}
}

func TestDescribeNamesEveryEffect(t *testing.T) {
	lines := strings.Join(pfDescribe(ipv4Spec), "\n")
	for _, wanted := range []string{
		"192.168.64.0/24", "8787",
		"/etc/pf.anchors/prison", "/etc/pf.conf",
		"/Library/LaunchDaemons/prison.firewall.plist",
		"sudo pfctl -f /etc/pf.conf", "sudo pfctl -E",
		"prison host firewall --remove",
	} {
		if !strings.Contains(lines, wanted) {
			t.Errorf("pfDescribe = %s, want %q", lines, wanted)
		}
	}
	if strings.Contains(lines, "neighbor discovery") {
		t.Error("pfDescribe has IPv6 rules for an IPv4 spec, want none")
	}
	if !strings.Contains(strings.Join(pfDescribe(Spec{
		SubnetV4:   "192.168.64.0/24",
		SubnetV6:   "fd00::/64",
		BrokerPort: 8787,
	}), "\n"), "fd00::/64") {
		t.Error("pfDescribe has no IPv6 subnet, want fd00::/64")
	}
}

func installEverything(t *testing.T, spec Spec, p paths) {
	t.Helper()
	writeFile(t, p.anchorFile, pfRules(spec))
	writeFile(t, p.mainRuleset,
		mainRulesetWithPrisonLines("scrub-anchor \"com.apple/*\"\n", p))
	writeFile(t, p.daemonFile, daemonPlist(p))
}

func TestStatusTransitions(t *testing.T) {
	ctx := context.Background()
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	runner := newRecordingRunner()
	runner.replies["pfctl -a prison -sr"] =
		"block drop in quick inet from 192.168.64.0/24 to any\n"

	writeFile(t, p.mainRuleset, "scrub-anchor \"com.apple/*\"\n")
	state, err := pfStatus(ctx, ipv4Spec, stagingDir, p, runner.run)
	if err != nil {
		t.Fatalf("pfStatus error = %v, want nil", err)
	}
	if state != StateMissing {
		t.Errorf("pfStatus = %q, want %q",
			state, StateMissing)
	}

	installEverything(t, ipv4Spec, p)
	state, err = pfStatus(ctx, ipv4Spec, stagingDir, p, runner.run)
	if err != nil {
		t.Fatalf("pfStatus error = %v, want nil", err)
	}
	if state != StateInstalled {
		t.Errorf("pfStatus = %q, want %q",
			state, StateInstalled)
	}

	writeFile(t, p.anchorFile, pfRules(Spec{
		SubnetV4:   "192.168.64.0/24",
		BrokerPort: 9999,
	}))
	state, _ = pfStatus(ctx, ipv4Spec, stagingDir, p, runner.run)
	if state != StateStale {
		t.Errorf("pfStatus = %q, want %q",
			state, StateStale)
	}

	installEverything(t, ipv4Spec, p)
	writeFile(t, p.mainRuleset, "scrub-anchor \"com.apple/*\"\n")
	state, _ = pfStatus(ctx, ipv4Spec, stagingDir, p, runner.run)
	if state != StateStale {
		t.Errorf("pfStatus = %q, want %q",
			state, StateStale)
	}

	installEverything(t, ipv4Spec, p)
	if err := os.Remove(p.daemonFile); err != nil {
		t.Fatalf("cannot remove the boot job: %v", err)
	}
	state, _ = pfStatus(ctx, ipv4Spec, stagingDir, p, runner.run)
	if state != StateStale {
		t.Errorf("pfStatus = %q, want %q",
			state, StateStale)
	}
}

func TestStatusWhenTheFilterCannotBeRead(t *testing.T) {
	ctx := context.Background()
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	installEverything(t, ipv4Spec, p)

	runner := newRecordingRunner()
	runner.failures["pfctl -a prison -sr"] = true
	state, err := pfStatus(ctx, ipv4Spec, stagingDir, p, runner.run)
	if err != nil {
		t.Fatalf("pfStatus error = %v, want nil", err)
	}
	if state != StateStale {
		t.Errorf("pfStatus = %q, want %q",
			state, StateStale)
	}

	writeFile(t, filepath.Join(stagingDir, EnableTokenName), "17\n")
	state, _ = pfStatus(ctx, ipv4Spec, stagingDir, p, runner.run)
	if state != StateInstalled {
		t.Errorf("pfStatus = %q, want %q",
			state, StateInstalled)
	}
}

func TestStatusWhenNothingIsLoaded(t *testing.T) {
	p := newTestPaths(t)
	installEverything(t, ipv4Spec, p)
	runner := newRecordingRunner()
	state, err := pfStatus(context.Background(), ipv4Spec, t.TempDir(), p,
		runner.run)
	if err != nil {
		t.Fatalf("pfStatus error = %v, want nil", err)
	}
	if state != StateStale {
		t.Errorf("pfStatus = %q, want %q",
			state, StateStale)
	}
}

func TestInstallCommandSequence(t *testing.T) {
	ctx := context.Background()
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	writeFile(t, p.mainRuleset, "scrub-anchor \"com.apple/*\"\n")

	runner := newRecordingRunner()
	runner.replies["sudo pfctl -E"] = "pf enabled\nToken : 4242\n"
	var out strings.Builder
	if err := pfInstall(ctx, ipv4Spec, stagingDir, p, runner.run, &out); err != nil {
		t.Fatalf("pfInstall error = %v, want nil", err)
	}

	rulesPath := filepath.Join(stagingDir, StagedRulesName)
	confPath := filepath.Join(stagingDir, StagedConfName)
	daemonPath := filepath.Join(stagingDir, StagedDaemonName)
	installArguments := "sudo install -m 0644 -o root -g wheel "
	checkCommands(t, runner.commands, []string{
		"pfctl -nf " + rulesPath,
		installArguments + rulesPath + " " + p.anchorFile,
		"pfctl -n -f " + confPath,
		installArguments + confPath + " " + p.mainRuleset,
		"sudo launchctl bootout system/prison.firewall",
		installArguments + daemonPath + " " + p.daemonFile,
		"sudo launchctl bootstrap system " + p.daemonFile,
		"sudo pfctl -f " + p.mainRuleset,
		"sudo pfctl -E",
	})

	staged, err := os.ReadFile(rulesPath)
	if err != nil {
		t.Fatalf("cannot read the staged rules: %v", err)
	}
	if string(staged) != pfRules(ipv4Spec) {
		t.Errorf("staged rules =\n%s, want pfRules", staged)
	}
	conf, err := os.ReadFile(confPath)
	if err != nil {
		t.Fatalf("cannot read the staged main ruleset: %v", err)
	}
	want := "scrub-anchor \"com.apple/*\"\n" + mainRulesetComment + "\n" +
		"anchor \"prison\"\n" +
		"load anchor \"prison\" from \"" + p.anchorFile + "\"\n"
	if string(conf) != want {
		t.Errorf("staged main ruleset =\n%s\nwant:\n%s", conf, want)
	}
	plist, err := os.ReadFile(daemonPath)
	if err != nil {
		t.Fatalf("cannot read the staged boot job: %v", err)
	}
	for _, wanted := range []string{
		"<string>prison.firewall</string>", "/sbin/pfctl -E",
		p.daemonMarkerFile,
	} {
		if !strings.Contains(string(plist), wanted) {
			t.Errorf("boot job has no %q, want it", wanted)
		}
	}
	token, err := os.ReadFile(filepath.Join(stagingDir, EnableTokenName))
	if err != nil {
		t.Fatalf("cannot read the enable token: %v", err)
	}
	if strings.TrimSpace(string(token)) != "4242" {
		t.Errorf("enable token = %q, want %q", token, "4242")
	}
	if !strings.Contains(out.String(), "drops rules") {
		t.Errorf("output = %q, want a reload warning", out.String())
	}
}

func TestInstallReleasesThePreviousToken(t *testing.T) {
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	writeFile(t, p.mainRuleset, "")
	writeFile(t, filepath.Join(stagingDir, EnableTokenName), "11\n")

	runner := newRecordingRunner()
	runner.replies["sudo pfctl -E"] = "Token : 12\n"
	err := pfInstall(context.Background(), ipv4Spec, stagingDir, p, runner.run,
		&strings.Builder{})
	if err != nil {
		t.Fatalf("pfInstall error = %v, want nil", err)
	}
	last := runner.commands[len(runner.commands)-1]
	if last != "sudo pfctl -X 11" {
		t.Errorf("last command = %q, want %q", last, "sudo pfctl -X 11")
	}
}

func TestInstallStopsWhenTheMainRulesetWouldNotParse(t *testing.T) {
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	writeFile(t, p.mainRuleset, "scrub-anchor \"com.apple/*\"\n")

	runner := newRecordingRunner()
	runner.failures["pfctl -n -f "+filepath.Join(stagingDir, StagedConfName)] = true
	err := pfInstall(context.Background(), ipv4Spec, stagingDir, p, runner.run,
		&strings.Builder{})
	if err == nil {
		t.Fatal("pfInstall error = nil, want an error")
	}
	if !strings.Contains(err.Error(), p.mainRuleset) {
		t.Errorf("error = %v, want it to contain %s", err, p.mainRuleset)
	}
	for _, command := range runner.commands {
		if strings.Contains(command, "pfctl -f") {
			t.Errorf("ran %q, want no reload", command)
		}
	}
}

func TestInstallWarnsWhenLaunchdRefusesTheJob(t *testing.T) {
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	writeFile(t, p.mainRuleset, "")

	runner := newRecordingRunner()
	runner.failures["sudo launchctl bootstrap system "+p.daemonFile] = true
	runner.failures["sudo launchctl load -w "+p.daemonFile] = true
	var out strings.Builder
	err := pfInstall(context.Background(), ipv4Spec, stagingDir, p, runner.run,
		&out)
	if err != nil {
		t.Fatalf("pfInstall error = %v, want nil", err)
	}
	if !strings.Contains(out.String(), "launchd did not load") {
		t.Errorf("output = %q, want a launchd warning", out.String())
	}
}

func TestRemoveCommandSequence(t *testing.T) {
	ctx := context.Background()
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	installEverything(t, ipv4Spec, p)
	writeFile(t, filepath.Join(stagingDir, EnableTokenName), "4242\n")

	runner := newRecordingRunner()
	runner.replies["sudo cat "+p.daemonMarkerFile] = "77\n"
	if err := pfRemove(ctx, stagingDir, p, runner.run, &strings.Builder{}); err != nil {
		t.Fatalf("pfRemove error = %v, want nil", err)
	}

	confPath := filepath.Join(stagingDir, StagedConfName)
	checkCommands(t, runner.commands, []string{
		"sudo cat " + p.daemonMarkerFile,
		"sudo launchctl bootout system/prison.firewall",
		"sudo launchctl unload -w " + p.daemonFile,
		"sudo rm -f " + p.daemonFile + " " + p.daemonMarkerFile,
		"sudo install -m 0644 -o root -g wheel " + confPath + " " + p.mainRuleset,
		"sudo rm -f " + p.anchorFile,
		"sudo pfctl -a prison -F rules",
		"sudo pfctl -f " + p.mainRuleset,
		"sudo pfctl -X 4242",
		"sudo pfctl -X 77",
	})

	conf, err := os.ReadFile(confPath)
	if err != nil {
		t.Fatalf("cannot read the staged main ruleset: %v", err)
	}
	if string(conf) != "scrub-anchor \"com.apple/*\"\n" {
		t.Errorf("staged main ruleset =\n%s, want only the scrub-anchor line", conf)
	}
	if _, err := os.Stat(filepath.Join(stagingDir, EnableTokenName)); err == nil {
		t.Error("enable token file exists, want it removed")
	}
}

func TestRemoveWithNothingInstalled(t *testing.T) {
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	writeFile(t, p.mainRuleset, "scrub-anchor \"com.apple/*\"\n")

	runner := newRecordingRunner()
	runner.failures["sudo cat "+p.daemonMarkerFile] = true
	if err := pfRemove(context.Background(), stagingDir, p, runner.run,
		&strings.Builder{}); err != nil {
		t.Fatalf("pfRemove error = %v, want nil", err)
	}
	checkCommands(t, runner.commands, []string{
		"sudo cat " + p.daemonMarkerFile,
		"sudo launchctl bootout system/prison.firewall",
		"sudo launchctl unload -w " + p.daemonFile,
		"sudo rm -f " + p.daemonFile + " " + p.daemonMarkerFile,
		"sudo rm -f " + p.anchorFile,
		"sudo pfctl -a prison -F rules",
		"sudo pfctl -f " + p.mainRuleset,
	})
}

func TestRemoveWarnsWhenTheMainRulesetCannotBeWritten(t *testing.T) {
	p := newTestPaths(t)
	stagingDir := t.TempDir()
	installEverything(t, ipv4Spec, p)

	runner := newRecordingRunner()
	confPath := filepath.Join(stagingDir, StagedConfName)
	runner.failures["sudo install -m 0644 -o root -g wheel "+confPath+" "+
		p.mainRuleset] = true
	var out strings.Builder
	if err := pfRemove(context.Background(), stagingDir, p, runner.run, &out); err != nil {
		t.Fatalf("pfRemove error = %v, want nil", err)
	}
	if !strings.Contains(out.String(), "cannot remove the prison lines") {
		t.Errorf("output = %q, want a warning", out.String())
	}
}

func TestMainRulesetEditsAreReversible(t *testing.T) {
	p := systemPaths()
	original := "scrub-anchor \"com.apple/*\"\nanchor \"com.apple/*\"\n"
	added := mainRulesetWithPrisonLines(original, p)
	if !mainRulesetCarriesAnchor(added, p) {
		t.Fatalf("mainRulesetCarriesAnchor = false after the add\n%s", added)
	}
	if again := mainRulesetWithPrisonLines(added, p); again != added {
		t.Errorf("second add =\n%s\nwant:\n%s", again, added)
	}
	back := mainRulesetWithoutPrisonLines(added, p)
	if back != original {
		t.Errorf("mainRulesetWithoutPrisonLines =\n%s\nwant:\n%s", back, original)
	}
	if mainRulesetCarriesAnchor(original, p) {
		t.Error("mainRulesetCarriesAnchor(original) = true, want false")
	}
}

func TestParseEnableToken(t *testing.T) {
	cases := map[string]string{
		"pf enabled\nToken : 4242\n":       "4242",
		"pfctl: pf already enabled\n":      "",
		"Token : 1\nToken : 2\n":           "1",
		"":                                 "",
		"No ALTQ support in kernel\nT : 9": "",
	}
	for output, want := range cases {
		if got := parseEnableToken(output); got != want {
			t.Errorf("parseEnableToken(%q) = %q, want %q", output, got, want)
		}
	}
}

func TestUnsupportedHost(t *testing.T) {
	if isSupportedOperatingSystem() {
		t.Skip("this host has an implemented packet filter")
	}
	ctx := context.Background()
	runner := newRecordingRunner()
	state, err := Status(ctx, ipv4Spec, t.TempDir(), runner.run)
	if err != nil || state != StateUnsupported {
		t.Errorf("Status = %q, %v, want %q, nil",
			state, err, StateUnsupported)
	}
	if err := Install(ctx, ipv4Spec, t.TempDir(), runner.run,
		&strings.Builder{}); err == nil {
		t.Error("Install error = nil, want an error")
	}
	if err := Remove(ctx, ipv4Spec, t.TempDir(), runner.run,
		&strings.Builder{}); err == nil {
		t.Error("Remove error = nil, want an error")
	}
	if len(runner.commands) != 0 {
		t.Errorf("commands = %v, want none", runner.commands)
	}
}
