package hostfw

import (
	"context"
	"fmt"
	"os"
	"strings"
)

const (
	nftTableName = "prison"
	nftUnitName  = "prison-firewall.service"
	// nfsPort is open because the aws-firecracker cage shares files over
	// NFS. The NFS server exports each folder to one box address only.
	nfsPort = 2049
)

type nftPaths struct {
	rulesFile string
	unitFile  string
}

func nftSystemPaths() nftPaths {
	return nftPaths{
		rulesFile: "/etc/prison/firewall.nft",
		unitFile:  "/etc/systemd/system/" + nftUnitName,
	}
}

// nftRules replaces the whole prison table at each load. Replies to
// connections from the host stay allowed, so the port forwarder works.
func nftRules(spec Spec) string {
	lines := []string{
		"#!/usr/sbin/nft -f",
		"# Generated by prison for the box network.",
		"table inet " + nftTableName,
		"delete table inet " + nftTableName,
		"table inet " + nftTableName + " {",
		"\tchain input {",
		"\t\ttype filter hook input priority filter; policy accept;",
		fmt.Sprintf("\t\tip saddr %s ct state established,related accept",
			spec.SubnetV4),
		fmt.Sprintf("\t\tip saddr %s tcp dport { %d, %d } accept",
			spec.SubnetV4, spec.BrokerPort, nfsPort),
		fmt.Sprintf("\t\tip saddr %s drop", spec.SubnetV4),
	}
	if spec.SubnetV6 != "" {
		lines = append(lines,
			fmt.Sprintf("\t\tip6 saddr %s drop", spec.SubnetV6))
	}
	lines = append(lines,
		"\t}",
		"\tchain forward {",
		"\t\ttype filter hook forward priority filter; policy accept;",
		fmt.Sprintf("\t\tip saddr %s drop", spec.SubnetV4),
		fmt.Sprintf("\t\tip daddr %s drop", spec.SubnetV4),
		"\t}",
		"}",
	)
	return strings.Join(lines, "\n") + "\n"
}

func nftUnit(p nftPaths) string {
	return strings.Join([]string{
		"[Unit]",
		"Description=prison box network firewall",
		"Before=network-pre.target",
		"Wants=network-pre.target",
		"",
		"[Service]",
		"Type=oneshot",
		"RemainAfterExit=yes",
		"ExecStart=/usr/sbin/nft -f " + p.rulesFile,
		"ExecStop=/usr/sbin/nft delete table inet " + nftTableName,
		"",
		"[Install]",
		"WantedBy=multi-user.target",
		"",
	}, "\n")
}

func nftReadCommand() string {
	return "sudo nft list table inet " + nftTableName
}

func nftDescribe(spec Spec) []string {
	p := nftSystemPaths()
	return []string{
		fmt.Sprintf("blocks all traffic from %s except tcp to ports %d "+
			"and %d", spec.SubnetV4, spec.BrokerPort, nfsPort),
		fmt.Sprintf("blocks forwarding to and from %s", spec.SubnetV4),
		fmt.Sprintf("writes the rules to %s, owned by root", p.rulesFile),
		fmt.Sprintf("writes %s, which loads the rules at boot", p.unitFile),
		"to undo, run `prison host firewall --remove`",
	}
}

// nftStatus reads files only, because listing nftables needs root.
func nftStatus(ctx context.Context, spec Spec, p nftPaths,
	run Runner) (State, error) {
	rules, err := os.ReadFile(p.rulesFile)
	rulesPresent := err == nil
	unitPresent := fileExists(p.unitFile)
	if !rulesPresent && !unitPresent {
		return StateMissing, nil
	}
	if !rulesPresent || !unitPresent || string(rules) != nftRules(spec) {
		return StateStale, nil
	}
	if _, err := run(ctx, "systemctl", "is-active", "--quiet",
		nftUnitName); err != nil {
		return StateStale, nil
	}
	return StateInstalled, nil
}

func nftInstall(ctx context.Context, spec Spec, stagingDir string,
	p nftPaths, run Runner) error {
	rulesPath, err := writeStagedFile(stagingDir, "nft-rules", nftRules(spec))
	if err != nil {
		return err
	}
	unitPath, err := writeStagedFile(stagingDir, "nft-unit", nftUnit(p))
	if err != nil {
		return err
	}
	steps := [][]string{
		{"sudo", "nft", "--check", "-f", rulesPath},
		{"sudo", "install", "-D", "-m", "0644", "-o", "root", "-g", "root",
			rulesPath, p.rulesFile},
		{"sudo", "install", "-m", "0644", "-o", "root", "-g", "root",
			unitPath, p.unitFile},
		{"sudo", "systemctl", "daemon-reload"},
		{"sudo", "systemctl", "enable", nftUnitName},
		{"sudo", "systemctl", "restart", nftUnitName},
	}
	for _, step := range steps {
		if output, err := run(ctx, step[0], step[1:]...); err != nil {
			return fmt.Errorf("`%s` failed: %w: %s", strings.Join(step, " "),
				err, strings.TrimSpace(output))
		}
	}
	return nil
}

func nftRemove(ctx context.Context, p nftPaths, run Runner) error {
	run(ctx, "sudo", "systemctl", "disable", "--now", nftUnitName)
	run(ctx, "sudo", "rm", "-f", p.unitFile, p.rulesFile)
	run(ctx, "sudo", "systemctl", "daemon-reload")
	run(ctx, "sudo", "nft", "delete", "table", "inet", nftTableName)
	return nil
}
