package hostfw

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const AnchorName = "prison"

// DaemonLabel names the launchd job that turns on pf at boot. macOS leaves
// pf off by default.
const DaemonLabel = "prison.firewall"

const (
	StagedRulesName  = "pf-rules"
	StagedConfName   = "pf-conf"
	StagedDaemonName = "pf-daemon.plist"
	EnableTokenName  = "pf-loaded"
)

const mainRulesetComment = "# prison, added by `prison firewall`."

type paths struct {
	anchorFile       string
	mainRuleset      string
	daemonFile       string
	daemonMarkerFile string
}

func systemPaths() paths {
	return paths{
		anchorFile:       "/etc/pf.anchors/" + AnchorName,
		mainRuleset:      "/etc/pf.conf",
		daemonFile:       "/Library/LaunchDaemons/" + DaemonLabel + ".plist",
		daemonMarkerFile: "/var/run/prison-firewall",
	}
}

func pfRules(spec Spec) string {
	anchorFile := systemPaths().anchorFile
	var text strings.Builder
	fmt.Fprintf(&text, "# Generated by prison for the box network.\n")
	fmt.Fprintf(&text, "# Installed at %s, which the main ruleset names,\n",
		anchorFile)
	fmt.Fprintf(&text, "# so the system loads these at every boot.\n")
	fmt.Fprintf(&text,
		"pass in quick inet proto tcp from %s to any port %d\n",
		spec.SubnetV4, spec.BrokerPort)
	fmt.Fprintf(&text,
		"pass in quick inet proto udp from %s to any port 67\n",
		spec.SubnetV4)
	fmt.Fprintf(&text, "block drop in quick inet from %s to any\n",
		spec.SubnetV4)
	if spec.SubnetV6 != "" {
		fmt.Fprintf(&text,
			"# Neighbour discovery keeps the box's address usable.\n")
		fmt.Fprintf(&text,
			"pass in quick inet6 proto ipv6-icmp from %s to any\n",
			spec.SubnetV6)
		fmt.Fprintf(&text, "block drop in quick inet6 from %s to any\n",
			spec.SubnetV6)
	}
	return text.String()
}

func pfReadCommand() string {
	return fmt.Sprintf("sudo pfctl -a %s -sr", AnchorName)
}

func pfDescribe(spec Spec) []string {
	p := systemPaths()
	lines := []string{
		fmt.Sprintf("blocks all traffic from %s except tcp to port %d and dhcp",
			spec.SubnetV4, spec.BrokerPort),
	}
	if spec.SubnetV6 != "" {
		lines = append(lines, fmt.Sprintf(
			"blocks all traffic from %s except neighbor discovery",
			spec.SubnetV6))
	}
	return append(lines,
		fmt.Sprintf("writes the rules to %s, owned by root", p.anchorFile),
		fmt.Sprintf("writes %s, 3 lines that load the rules at boot",
			p.mainRuleset),
		fmt.Sprintf("writes %s, a job that turns on the filter at boot",
			p.daemonFile),
		fmt.Sprintf("runs sudo pfctl -f %s", p.mainRuleset),
		"runs sudo pfctl -E",
		"to undo, run `prison host firewall --remove`",
	)
}

func mainRulesetLines(p paths) []string {
	return []string{
		mainRulesetComment,
		fmt.Sprintf("anchor %q", AnchorName),
		loadAnchorLine(p),
	}
}

func loadAnchorLine(p paths) string {
	return fmt.Sprintf("load anchor %q from %q", AnchorName, p.anchorFile)
}

func readMainRuleset(p paths) (string, error) {
	content, err := os.ReadFile(p.mainRuleset)
	if errors.Is(err, os.ErrNotExist) {
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("cannot read %s: %w", p.mainRuleset, err)
	}
	return string(content), nil
}

func mainRulesetWithoutPrisonLines(content string, p paths) string {
	prisonLines := mainRulesetLines(p)
	var kept []string
	for _, line := range strings.Split(content, "\n") {
		isPrisonLine := false
		for _, prisonLine := range prisonLines {
			if line == prisonLine {
				isPrisonLine = true
				break
			}
		}
		if !isPrisonLine {
			kept = append(kept, line)
		}
	}
	return endWithNewline(strings.Join(kept, "\n"))
}

func mainRulesetWithPrisonLines(content string, p paths) string {
	stripped := mainRulesetWithoutPrisonLines(content, p)
	return stripped + strings.Join(mainRulesetLines(p), "\n") + "\n"
}

func mainRulesetCarriesAnchor(content string, p paths) bool {
	wanted := loadAnchorLine(p)
	for _, line := range strings.Split(content, "\n") {
		if line == wanted {
			return true
		}
	}
	return false
}

func endWithNewline(text string) string {
	if text == "" || strings.HasSuffix(text, "\n") {
		return text
	}
	return text + "\n"
}

func daemonPlist(p paths) string {
	command := fmt.Sprintf(
		"/sbin/pfctl -E 2&gt;&amp;1 | /usr/bin/awk '/Token/ { print $NF; exit }' &gt; %s",
		p.daemonMarkerFile)
	return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>` + DaemonLabel + `</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>-c</string>
    <string>` + command + `</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
`
}

func parseEnableToken(output string) string {
	for _, line := range strings.Split(output, "\n") {
		if !strings.Contains(line, "Token") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		return fields[len(fields)-1]
	}
	return ""
}

func installAsRoot(ctx context.Context, run Runner, source, target string) error {
	_, err := run(ctx, "sudo", "install", "-m", "0644", "-o", "root",
		"-g", "wheel", source, target)
	if err != nil {
		return fmt.Errorf("cannot write %s: %w", target, err)
	}
	return nil
}

func pfStatus(ctx context.Context, spec Spec, stagingDir string, p paths, run Runner) (State, error) {
	anchorContent, err := os.ReadFile(p.anchorFile)
	anchorMissing := errors.Is(err, os.ErrNotExist)
	if err != nil && !anchorMissing {
		return StateMissing, fmt.Errorf("cannot read %s: %w",
			p.anchorFile, err)
	}
	ruleset, err := readMainRuleset(p)
	if err != nil {
		return StateMissing, err
	}
	carriesAnchor := mainRulesetCarriesAnchor(ruleset, p)
	daemonInstalled := fileExists(p.daemonFile)

	if anchorMissing && !carriesAnchor && !daemonInstalled {
		return StateMissing, nil
	}
	if anchorMissing || !carriesAnchor || !daemonInstalled {
		return StateStale, nil
	}
	if string(anchorContent) != pfRules(spec) {
		return StateStale, nil
	}

	loaded, err := run(ctx, "pfctl", "-a", AnchorName, "-sr")
	if err != nil {
		if fileExists(filepath.Join(stagingDir, EnableTokenName)) {
			return StateInstalled, nil
		}
		return StateStale, nil
	}
	if strings.TrimSpace(loaded) == "" {
		return StateStale, nil
	}
	return StateInstalled, nil
}

func pfInstall(ctx context.Context, spec Spec, stagingDir string, p paths, run Runner, out io.Writer) error {
	rulesPath, err := writeStagedFile(stagingDir, StagedRulesName, pfRules(spec))
	if err != nil {
		return err
	}
	if _, err := run(ctx, "pfctl", "-nf", rulesPath); err != nil {
		return fmt.Errorf("the prison rules at %s do not parse: %w",
			rulesPath, err)
	}
	if err := installAsRoot(ctx, run, rulesPath, p.anchorFile); err != nil {
		return err
	}

	ruleset, err := readMainRuleset(p)
	if err != nil {
		return err
	}
	confPath, err := writeStagedFile(stagingDir, StagedConfName,
		mainRulesetWithPrisonLines(ruleset, p))
	if err != nil {
		return err
	}
	// pf rejects the whole ruleset when one line fails to parse.
	if _, err := run(ctx, "pfctl", "-n", "-f", confPath); err != nil {
		return fmt.Errorf("the new main ruleset at %s does not parse. "+
			"%s did not change: %w", confPath, p.mainRuleset, err)
	}
	if err := installAsRoot(ctx, run, confPath, p.mainRuleset); err != nil {
		return err
	}

	daemonPath, err := writeStagedFile(stagingDir, StagedDaemonName,
		daemonPlist(p))
	if err != nil {
		return err
	}
	run(ctx, "sudo", "launchctl", "bootout", "system/"+DaemonLabel)
	if err := installAsRoot(ctx, run, daemonPath, p.daemonFile); err != nil {
		return err
	}
	if _, err := run(ctx, "sudo", "launchctl", "bootstrap", "system",
		p.daemonFile); err != nil {
		if _, err := run(ctx, "sudo", "launchctl", "load", "-w",
			p.daemonFile); err != nil {
			fmt.Fprintf(out, "warn: launchd did not load %s. pf is off. "+
				"Run `prison host firewall` again.\n", p.daemonFile)
		}
	}

	fmt.Fprintf(out, "warn: reloading %s drops rules from other tools, "+
		"such as a VPN. Restart those tools.\n", p.mainRuleset)
	if _, err := run(ctx, "sudo", "pfctl", "-f", p.mainRuleset); err != nil {
		return fmt.Errorf("cannot load the main ruleset. The prison rules at %s "+
			"are not active: %w", p.anchorFile, err)
	}

	return holdEnableReference(ctx, stagingDir, run)
}

// holdEnableReference keeps one pf enable reference for prison. It
// releases the previous reference so that references do not pile up.
func holdEnableReference(ctx context.Context, stagingDir string, run Runner) error {
	tokenPath := filepath.Join(stagingDir, EnableTokenName)
	previous, _ := os.ReadFile(tokenPath)
	previousToken := strings.TrimSpace(string(previous))

	output, _ := run(ctx, "sudo", "pfctl", "-E")
	token := parseEnableToken(output)
	if err := os.WriteFile(tokenPath, []byte(token+"\n"), 0o600); err != nil {
		return fmt.Errorf("cannot write %s: %w", tokenPath, err)
	}
	if previousToken != "" && previousToken != token {
		run(ctx, "sudo", "pfctl", "-X", previousToken)
	}
	return nil
}

func pfRemove(ctx context.Context, stagingDir string, p paths, run Runner, out io.Writer) error {
	bootTokenOutput, err := run(ctx, "sudo", "cat", p.daemonMarkerFile)
	bootToken := ""
	if err == nil {
		bootToken = strings.TrimSpace(bootTokenOutput)
	}

	run(ctx, "sudo", "launchctl", "bootout", "system/"+DaemonLabel)
	run(ctx, "sudo", "launchctl", "unload", "-w", p.daemonFile)
	run(ctx, "sudo", "rm", "-f", p.daemonFile, p.daemonMarkerFile)

	ruleset, err := readMainRuleset(p)
	if err != nil {
		return err
	}
	if mainRulesetCarriesAnchor(ruleset, p) {
		confPath, err := writeStagedFile(stagingDir, StagedConfName,
			mainRulesetWithoutPrisonLines(ruleset, p))
		if err != nil {
			return err
		}
		if err := installAsRoot(ctx, run, confPath, p.mainRuleset); err != nil {
			fmt.Fprintf(out, "warn: cannot remove the prison lines from %s.\n",
				p.mainRuleset)
		}
	}
	run(ctx, "sudo", "rm", "-f", p.anchorFile)

	run(ctx, "sudo", "pfctl", "-a", AnchorName, "-F", "rules")
	run(ctx, "sudo", "pfctl", "-f", p.mainRuleset)

	tokenPath := filepath.Join(stagingDir, EnableTokenName)
	held, _ := os.ReadFile(tokenPath)
	// Releasing only the prison references keeps pf on for other users.
	for _, token := range []string{strings.TrimSpace(string(held)), bootToken} {
		if token == "" {
			continue
		}
		run(ctx, "sudo", "pfctl", "-X", token)
	}
	if err := os.Remove(tokenPath); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("cannot remove %s: %w", tokenPath, err)
	}
	return nil
}
